# Generated by Django 5.2.4 on 2025-07-03 05:20

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):
    operations = [
        VectorExtension()
    ]