# Generated by Django 5.2.4 on 2025-07-03 07:21

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
